# Generated by Django 4.2 on 2023-04-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='age1',
            field=models.IntegerField(null=True),
        ),
    ]
