# Generated by Django 4.2 on 2023-04-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
    ]
