# Generated by Django 4.2 on 2023-04-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_blog_age2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
