# Generated by Django 4.2 on 2023-04-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_blog_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
